vscode:
  extensions:
    - dsznajder.es7-react-js-snippets
    - giantcola.advanced-new-file
    - hbenl.vscode-test-explorer
    - kavod-io.vscode-jest-test-adapter
    - esbenp.prettier-vscode

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser

github:
  prebuilds:
    branches: true

tasks:
  - init: yarn
